[package]
name = "ts_quote"
version = "0.6.0"
authors = ["Spencer Kohan <spencerkohan@gmail.com>"]
edition = "2021"
description = "Procedural macros for quasi-quoting TypeScript from Rust"
license = "Apache-2.0"

repository = "https://github.com/spencerkohan/type_reflect/tree/main/ts_quote"
documentation = "https://docs.rs/ts_quote"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["deno_ast"]
deno_ast = ["dep:deno_ast", "dep:dprint-plugin-typescript"]

[dependencies]
ts_quote_macros = "0.5.0"
anyhow = "1.0.75"
deno_ast = { version = "0.31.6", optional = true }
dprint-plugin-typescript = { version = "0.88.3", optional = true }

[[example]]
name = "string_only"

[[example]]
name = "ts_quote_examples"
required-features = ["deno_ast"]
